# Generated by Django 5.2.3 on 2025-06-27 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supertone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voice_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('style_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperToneLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('style', models.CharField(choices=[('neutral', '일반'), ('happy', '기쁨')], default='neutral', max_length=10)),
                ('language', models.CharField(choices=[('ko', 'Korean'), ('en', 'English'), ('jp', 'Japanese')], default='ko', max_length=10)),
                ('model', models.CharField(choices=[('sona_speech_1', 'Sona Speech 1')], default='sona_speech_1', max_length=30)),
                ('order', models.PositiveIntegerField()),
                ('supertone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='supertone.supertone')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='supertone.voice')),
            ],
        ),
    ]
