# Generated by Django 5.2.3 on 2025-06-27 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supertone', '0002_voice_voicestyle_supertoneline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='id',
        ),
        migrations.AlterField(
            model_name='supertoneline',
            name='voice',
            field=models.ForeignKey(default='e5f6fb1a53d0add87afb4f', on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='supertone.voice'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
