# Generated by Django 5.2.3 on 2025-06-27 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supertone', '0003_remove_voice_id_alter_supertoneline_voice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supertoneline',
            name='voice',
            field=models.ForeignKey(db_column='voice_id', default='e5f6fb1a53d0add87afb4f', on_delete=django.db.models.deletion.PROTECT, to='supertone.voice'),
        ),
    ]
