# Generated by Django 5.2.3 on 2025-06-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supertone', '0005_alter_voice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supertoneline',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='supertone/audio/'),
        ),
        migrations.AlterField(
            model_name='supertoneline',
            name='style',
            field=models.CharField(choices=[('neutral', '일반'), ('happy', '기쁨'), ('serene', '고요한')], default='neutral', max_length=10),
        ),
    ]
