# Generated by Django 5.2.3 on 2025-06-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supertone', '0006_supertoneline_audio_file_alter_supertoneline_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supertoneline',
            options={'ordering': ['order']},
        ),
    ]
