# Generated by Django 5.2.3 on 2025-06-27 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supertone', '0007_alter_supertoneline_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supertone',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='supertone/audio/'),
        ),
        migrations.AddField(
            model_name='supertone',
            name='language',
            field=models.CharField(choices=[('ko', 'Korean'), ('en', 'English'), ('jp', 'Japanese')], default='ko', max_length=10),
        ),
        migrations.AddField(
            model_name='supertone',
            name='model',
            field=models.CharField(choices=[('sona_speech_1', 'Sona Speech 1')], default='sona_speech_1', max_length=30),
        ),
        migrations.AddField(
            model_name='supertone',
            name='pitch_shift',
            field=models.IntegerField(default=0, help_text='음정의 높낮이를 조정합니다. 0은 원래 보이스 음정이며 ±12까지 가능합니다.'),
        ),
        migrations.AddField(
            model_name='supertone',
            name='pitch_variance',
            field=models.FloatField(default=1, help_text='발화 중 억양 변화 정도를 조절합니다. 0.1~2 사이의 값을 가집니다.'),
        ),
        migrations.AddField(
            model_name='supertone',
            name='speed',
            field=models.FloatField(default=1, help_text='발화 속도를 조절합니다. 0.5~2 사이의 값을 가집니다.'),
        ),
        migrations.AddField(
            model_name='supertone',
            name='style',
            field=models.CharField(choices=[('neutral', '일반'), ('happy', '기쁨'), ('serene', '고요한')], default='neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='supertone',
            name='voice',
            field=models.ForeignKey(db_column='voice_id', default='e5f6fb1a53d0add87afb4f', on_delete=django.db.models.deletion.PROTECT, to='supertone.voice'),
        ),
        migrations.AddField(
            model_name='supertoneline',
            name='pitch_shift',
            field=models.IntegerField(default=0, help_text='음정의 높낮이를 조정합니다. 0은 원래 보이스 음정이며 ±12까지 가능합니다.'),
        ),
        migrations.AddField(
            model_name='supertoneline',
            name='pitch_variance',
            field=models.FloatField(default=1, help_text='발화 중 억양 변화 정도를 조절합니다. 0.1~2 사이의 값을 가집니다.'),
        ),
        migrations.AddField(
            model_name='supertoneline',
            name='speed',
            field=models.FloatField(default=1, help_text='발화 속도를 조절합니다. 0.5~2 사이의 값을 가집니다.'),
        ),
    ]
