# Generated by Django 5.2.3 on 2025-06-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supertone', '0008_supertone_audio_file_supertone_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supertone',
            name='text',
            field=models.TextField(default='음성을 미리 만들어볼 수 있어요. 세팅한 음성은 다음과 같이 나옵니다.'),
            preserve_default=False,
        ),
    ]
