# Generated by Django 5.2.3 on 2025-06-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supertone', '0009_supertone_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voice',
            name='models',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='voice',
            name='samples',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='voice',
            name='styles',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='voice',
            name='user_case',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
