# Generated by Django 5.2.3 on 2025-06-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supertone', '0010_voice_gender_voice_models_voice_samples_voice_styles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supertone',
            name='style',
            field=models.CharField(choices=[('neutral', '일반')], default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='supertoneline',
            name='style',
            field=models.CharField(choices=[('neutral', '일반')], default='neutral', max_length=10),
        ),
    ]
