# Generated by Django 5.2.3 on 2025-06-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supertone', '0011_alter_supertone_style_alter_supertoneline_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supertone',
            name='style',
            field=models.CharField(default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='supertoneline',
            name='style',
            field=models.CharField(default='neutral', max_length=10),
        ),
    ]
