# Generated by Django 5.2.3 on 2025-07-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supertone', '0013_alter_supertone_style_alter_supertoneline_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voice',
            name='thumbnail_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
