# Generated by Django 5.2.3 on 2025-07-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supertone', '0014_voice_description_voice_thumbnail_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
