# Generated by Django 5.2.3 on 2025-07-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supertone", "0015_voice_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="supertoneline",
            name="silent",
            field=models.FloatField(
                default=0.3,
                help_text="초 단위 무음 구간 길이입니다. (소수점 자릿수 제한 없음, 기본값 0.3초)",
            ),
        ),
    ]
